dkp_value_table = {
{["loot_id"]="45540",["loot_name"] = "Bladebearer's Signet",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Trash",},
{["loot_id"]="45605",["loot_name"] = "Daschal's Bite",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Trash",},
{["loot_id"]="45542",["loot_name"] = "Greaves of the Stonewarder",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Trash",},
{["loot_id"]="45549",["loot_name"] = "Grips of Chaos",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Trash",},
{["loot_id"]="45544",["loot_name"] = "Leggings of the Tortured Earth",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Trash",},
{["loot_id"]="45539",["loot_name"] = "Pendant of Focused Energies",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Trash",},
{["loot_id"]="45547",["loot_name"] = "Relic Hunter's Cord",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Trash",},
{["loot_id"]="45543",["loot_name"] = "Shoulders of Misfortune",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Trash",},
{["loot_id"]="45541",["loot_name"] = "Shroud of Alteration",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Trash",},
{["loot_id"]="45538",["loot_name"] = "Titanstone Pendant",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Trash",},
{["loot_id"]="46027",["loot_name"] = "Formula: Enchant Weapon - Blade Ward",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="46348",["loot_name"] = "Formula: Enchant Weapon - Blood Draining",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45100",["loot_name"] = "Pattern: Belt of Arctic Life",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45094",["loot_name"] = "Pattern: Belt of Dragons",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45096",["loot_name"] = "Pattern: Blue Belt of Chaos",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45095",["loot_name"] = "Pattern: Boots of Living Scale",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45101",["loot_name"] = "Pattern: Boots of Wintry Endurance",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45104",["loot_name"] = "Pattern: Cord of the White Dawn",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45098",["loot_name"] = "Pattern: Death-warmed Belt",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45099",["loot_name"] = "Pattern: Footpads of Silence",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45097",["loot_name"] = "Pattern: Lightning Grounded Boots",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45102",["loot_name"] = "Pattern: Sash of Ancient Power",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45105",["loot_name"] = "Pattern: Savior's Slippers",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45103",["loot_name"] = "Pattern: Spellslinger's Slippers",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45089",["loot_name"] = "Plans: Battlelord's Plate Boots",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45088",["loot_name"] = "Plans: Belt of the Titans",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45092",["loot_name"] = "Plans: Indestructible Plate Girdle",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45090",["loot_name"] = "Plans: Plate Girdle of Righteousness",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45093",["loot_name"] = "Plans: Spiked Deathdealers",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45091",["loot_name"] = "Plans: Treads of Destiny",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Recipes",},
{["loot_id"]="45038",["loot_name"] = "Fragment of Val'anyr",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Tokens",},
{["loot_id"]="45087",["loot_name"] = "Runed Orb",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Tokens",},
{["loot_id"]="45135",["loot_name"] = "Boots of Fiery Resolution",["loot_value"] = "HPal - Bis 2 HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45117",["loot_name"] = "Constructor's Handwraps",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45119",["loot_name"] = "Embrace of the Leviathan",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45116",["loot_name"] = "Freya's Choker of Warding",["loot_value"] = "HPal - Bis No HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45109",["loot_name"] = "Gloves of the Fiery Behemoth",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45113",["loot_name"] = "Glowing Ring of Reclamation",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45132",["loot_name"] = "Golden Saronite Dragon",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45107",["loot_name"] = "Iron Riveted War Helm",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45115",["loot_name"] = "Leviathan Fueling Manual",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45108",["loot_name"] = "Mechanist's Bindings",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45111",["loot_name"] = "Mimiron's Inferno Couplings",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45133",["loot_name"] = "Pendant of Fiery Havoc",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45134",["loot_name"] = "Plated Leggings of Ruination",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45086",["loot_name"] = "Rising Sun",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45136",["loot_name"] = "Shoulderpads of Dormant Energies",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45114",["loot_name"] = "Steamcaller's Totem",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45118",["loot_name"] = "Steamworker's Goggles",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45106",["loot_name"] = "Strength of the Automaton",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45112",["loot_name"] = "The Leviathan's Coil",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45110",["loot_name"] = "Titanguard",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45166",["loot_name"] = "Charred Saronite Greaves",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45157",["loot_name"] = "Cindershard Ring",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45162",["loot_name"] = "Flamestalker Boots",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45185",["loot_name"] = "Flamewrought Cinch",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45161",["loot_name"] = "Girdle of Embers",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45158",["loot_name"] = "Heart of Iron",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45164",["loot_name"] = "Helm of the Furnace Master",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45171",["loot_name"] = "Intensity",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45167",["loot_name"] = "Lifeforge Breastplate",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45168",["loot_name"] = "Pyrelight Circle",["loot_value"] = "HPal - Bis No HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45170",["loot_name"] = "Scepter of Creation",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45186",["loot_name"] = "Soot-Covered Mantle",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45169",["loot_name"] = "Totem of the Dancing Flame",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45165",["loot_name"] = "Worldcarver",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45187",["loot_name"] = "Wristguards of the Firetender",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Ignis",},
{["loot_id"]="45151",["loot_name"] = "Belt of the Fallen Wyrm",["loot_value"] = "HPal - Bis No HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45149",["loot_name"] = "Bracers of the Broodmother",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45150",["loot_name"] = "Collar of the Wyrmhunter",["loot_value"] = "BIS NO HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45139",["loot_name"] = "Dragonslayer's Brace",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45138",["loot_name"] = "Drape of the Drakerider",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45147",["loot_name"] = "Guiding Star",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45510",["loot_name"] = "Libram of Discord",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45148",["loot_name"] = "Living Flame",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45141",["loot_name"] = "Proto-hide Leggings",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45140",["loot_name"] = "Razorscale Shoulderguards",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45142",["loot_name"] = "Remorse",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45143",["loot_name"] = "Saronite Mesh Legguards",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45146",["loot_name"] = "Shackles of the Odalisque",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45144",["loot_name"] = "Sigil of Deflection",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45137",["loot_name"] = "Veranus' Bane",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45260",["loot_name"] = "Boots of Hasty Revival",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45249",["loot_name"] = "Brass-lined Boots",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45445",["loot_name"] = "Breastplate of the Devoted",["loot_value"] = "HPal - Bis Phase HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45443",["loot_name"] = "Charm of Meticulous Timing",["loot_value"] = "HPal - Bis HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45248",["loot_name"] = "Clockwork Legplates",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45250",["loot_name"] = "Crazed Construct Ring",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45444",["loot_name"] = "Gloves of the Steady Hand",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45246",["loot_name"] = "Golem-Shard Sticker",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45446",["loot_name"] = "Grasps of Reason",["loot_value"] = "BIS",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45252",["loot_name"] = "Horologist's Wristguards",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45253",["loot_name"] = "Mantle of Wavering Calm",["loot_value"] = "Good",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45257",["loot_name"] = "Quartz Crystal Wand",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45259",["loot_name"] = "Quartz-studded Harness",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45258",["loot_name"] = "Sandals of Rash Temperament",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45251",["loot_name"] = "Shoulderplates of the Deconstructor",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45254",["loot_name"] = "Sigil of the Vengeful Heart",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45247",["loot_name"] = "Signet of the Earthshaker",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45442",["loot_name"] = "Sorthalis, Hammer of the Watchers",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45255",["loot_name"] = "Thunderfall Totem",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45256",["loot_name"] = "Twisted Visage",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "XT-002",},
{["loot_id"]="45226",["loot_name"] = "Ancient Iron Heaume",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45241",["loot_name"] = "Belt of Colossal Rage",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45242",["loot_name"] = "Drape of Mortal Downfall",["loot_value"] = "2eme bis",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45224",["loot_name"] = "Drape of the Lithe",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45607",["loot_name"] = "Fang of Oblivion",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45244",["loot_name"] = "Greaves of Swift Vengeance",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45228",["loot_name"] = "Handguards of the Enclave",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45193",["loot_name"] = "Insurmountable Fervor",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45227",["loot_name"] = "Iron-studded Mantle",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45238",["loot_name"] = "Overload Legwraps",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45237",["loot_name"] = "Phaelia's Vestments of the Sprouting Seed",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45235",["loot_name"] = "Radiant Seal",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45240",["loot_name"] = "Raiments of the Iron Council",["loot_value"] = "BIS Support",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45234",["loot_name"] = "Rapture",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45232",["loot_name"] = "Runed Ironhide Boots",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45239",["loot_name"] = "Runeshaper's Gloves",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45243",["loot_name"] = "Sapphire Amulet of Renewal",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45245",["loot_name"] = "Shoulderpads of the Intruder",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45225",["loot_name"] = "Steelbreaker's Embrace",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45233",["loot_name"] = "Stormrune Edge",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45236",["loot_name"] = "Unblinking Eye",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Assembly",},
{["loot_id"]="45275",["loot_name"] = "Bracers of Unleashed Magic",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45264",["loot_name"] = "Decimator's Armguards",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45261",["loot_name"] = "Giant's Bane",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45268",["loot_name"] = "Gloves of the Pythonic Guardian",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45273",["loot_name"] = "Handwraps of Plentiful Recovery",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45270",["loot_name"] = "Idol of the Crying Wind",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45271",["loot_name"] = "Ironmender",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45274",["loot_name"] = "Leggings of the Stoneweaver",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45266",["loot_name"] = "Malice",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45262",["loot_name"] = "Necklace of Unerring Mettle",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45272",["loot_name"] = "Robes of the Umbral Brute",["loot_value"] = "Great",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45267",["loot_name"] = "Saronite Plated Legguards",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45265",["loot_name"] = "Shoulderpads of the Monolith",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45269",["loot_name"] = "Unfaltering Armguards",["loot_value"] = "HPal - Bis No HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45263",["loot_name"] = "Wrathstone",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45440",["loot_name"] = "Amice of the Stoic Watch",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45319",["loot_name"] = "Cloak of the Makers",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45435",["loot_name"] = "Cowl of the Absolute",["loot_value"] = "Great",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45325",["loot_name"] = "Gloves of the Stonereaper",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45434",["loot_name"] = "Greaves of the Rockmender",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45436",["loot_name"] = "Libram of the Resolute",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45326",["loot_name"] = "Platinum Band of the Aesir",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45438",["loot_name"] = "Ring of the Faithful Servant",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45437",["loot_name"] = "Runescribed Blade",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45441",["loot_name"] = "Sandals of the Ancient Keeper",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45320",["loot_name"] = "Shoulderplates of the Eternal",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45327",["loot_name"] = "Siren's Cry",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45315",["loot_name"] = "Stonerender",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45334",["loot_name"] = "Unbreakable Chestguard",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45439",["loot_name"] = "Unwavering Stare",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45610",["loot_name"] = "Boundless Gaze",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45587",["loot_name"] = "Bulwark of Algalon",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45609",["loot_name"] = "Comet's Trail",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},                                                                                                                                                                                                                                                                                                                                                                                                  9",["loot_name"] = "Comet's Trail",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45612",["loot_name"] = "Constellus",["loot_value"] = "HPal - Bis HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45617",["loot_name"] = "Cosmos",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45613",["loot_name"] = "Dreambinder",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45607",["loot_name"] = "Fang of Oblivion",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45594",["loot_name"] = "Legplates of the Endless Void",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45665",["loot_name"] = "Pharos Gloves",["loot_value"] = "ALL BIS",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45615",["loot_name"] = "Planewalker Treads",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="46053",["loot_name"] = "Reply-Code Alpha",["loot_value"] = "HPal - Bis HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45599",["loot_name"] = "Sabatons of Lifeless Night",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45570",["loot_name"] = "Skyforge Crossbow",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45611",["loot_name"] = "Solar Bindings",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45616",["loot_name"] = "Star-beaded Clutch",["loot_value"] = "HPal - Bis HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45620",["loot_name"] = "Starshard Edge",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45619",["loot_name"] = "Starwatcher's Binding",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Algalon",},
{["loot_id"]="45484",["loot_name"] = "Bladetwister",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Freya",},
{["loot_id"]="45483",["loot_name"] = "Boots of the Servant",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Freya",},
{["loot_id"]="45485",["loot_name"] = "Bronze Pendant of the Vanir",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Freya",},
{["loot_id"]="45486",["loot_name"] = "Drape of the Sullen Goddess",["loot_value"] = "HPal - Bis Phase HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Freya",},
{["loot_id"]="45613",["loot_name"] = "Dreambinder",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Freya",},
{["loot_id"]="45481",["loot_name"] = "Gauntlets of Ruthless Reprisal",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Freya",},
{["loot_id"]="45487",["loot_name"] = "Handguards of Revitalization",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Freya",},
{["loot_id"]="45488",["loot_name"] = "Leggings of the Enslaved Idol",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Freya",},
{["loot_id"]="45482",["loot_name"] = "Leggings of the Lifetender",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Freya",},
{["loot_id"]="45653",["loot_name"] = "Legplates of the Wayward Conqueror",["loot_value"] = "HPal - Bis Phase",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Freya",},
{["loot_id"]="45654",["loot_name"] = "Legplates of the Wayward Protector",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Freya",},
{["loot_id"]="45655",["loot_name"] = "Legplates of the Wayward Vanquisher",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Freya",},
{["loot_id"]="45480",["loot_name"] = "Nymph Heart Charm",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Freya",},
{["loot_id"]="45479",["loot_name"] = "The Lifebinder",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Freya",},
{["loot_id"]="45460",["loot_name"] = "Bindings of Winter Gale",["loot_value"] = "HPal - Bis HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Hodir",},
{["loot_id"]="45632",["loot_name"] = "Breastplate of the Wayward Conqueror",["loot_value"] = "Great",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Hodir",},
{["loot_id"]="45633",["loot_name"] = "Breastplate of the Wayward Protector",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Hodir",},
{["loot_id"]="45634",["loot_name"] = "Breastplate of the Wayward Vanquisher",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Hodir",},
{["loot_id"]="45461",["loot_name"] = "Drape of Icy Intent",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Hodir",},
{["loot_id"]="45459",["loot_name"] = "Frigid Strength of Hodir",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Hodir",},
{["loot_id"]="45454",["loot_name"] = "Frost-bound Chain Bracers",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Hodir",},
{["loot_id"]="45452",["loot_name"] = "Frostplate Greaves",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Hodir",},
{["loot_id"]="45451",["loot_name"] = "Frozen Loop",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Hodir",},
{["loot_id"]="45462",["loot_name"] = "Gloves of the Frozen Glade",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Hodir",},
{["loot_id"]="45450",["loot_name"] = "Northern Barrier",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Hodir",},
{["loot_id"]="45457",["loot_name"] = "Staff of Endless Winter",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Hodir",},
{["loot_id"]="45453",["loot_name"] = "Winter's Icy Embrace",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Hodir",},
{["loot_id"]="45467",["loot_name"] = "Belt of the Betrayed",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Thorim",},
{["loot_id"]="45638",["loot_name"] = "Crown of the Wayward Conqueror",["loot_value"] = "Hpal - Bis Phase",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Thorim",},
{["loot_id"]="45639",["loot_name"] = "Crown of the Wayward Protector",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Thorim",},
{["loot_id"]="45640",["loot_name"] = "Crown of the Wayward Vanquisher",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Thorim",},
{["loot_id"]="45473",["loot_name"] = "Embrace of the Gladiator",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Thorim",},
{["loot_id"]="45471",["loot_name"] = "Fate's Clutch",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Thorim",},
{["loot_id"]="45468",["loot_name"] = "Leggings of Lost Love",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Thorim",},
{["loot_id"]="45474",["loot_name"] = "Pauldrons of the Combatant",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Thorim",},
{["loot_id"]="45466",["loot_name"] = "Scale of Fates",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Thorim",},
{["loot_id"]="45469",["loot_name"] = "Sif's Promise",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Thorim",},
{["loot_id"]="45570",["loot_name"] = "Skyforge Crossbow",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Thorim",},
{["loot_id"]="45463",["loot_name"] = "Vulmir, the Northern Tempest",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Thorim",},
{["loot_id"]="45472",["loot_name"] = "Warhelm of the Champion",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Thorim",},
{["loot_id"]="45470",["loot_name"] = "Wisdom's Hold",["loot_value"] = "HPal - Bis HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Thorim",},
{["loot_id"]="45663",["loot_name"] = "Armbands of Bedlam",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45493",["loot_name"] = "Asimov's Drape",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45495",["loot_name"] = "Conductive Seal",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45497",["loot_name"] = "Crown of Luminescence",["loot_value"] = "ALL BIS",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45494",["loot_name"] = "Delirium's Touch",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45641",["loot_name"] = "Gauntlets of the Wayward Conqueror",["loot_value"] = "Hpal - Bis Phase",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45642",["loot_name"] = "Gauntlets of the Wayward Protector",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45643",["loot_name"] = "Gauntlets of the Wayward Vanquisher",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45489",["loot_name"] = "Insanity's Grip",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45492",["loot_name"] = "Malleable Steelweave Mantle",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45490",["loot_name"] = "Pandora's Plea",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45620",["loot_name"] = "Starshard Edge",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45496",["loot_name"] = "Titanskin Cloak",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45491",["loot_name"] = "Waistguard of the Creator",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45505",["loot_name"] = "Belt of Clinging Hope",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45508",["loot_name"] = "Belt of the Darkspeaker",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45513",["loot_name"] = "Boots of the Forgotten Depths",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45501",["loot_name"] = "Boots of the Underdweller",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45504",["loot_name"] = "Darkcore Leggings",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45518",["loot_name"] = "Flare of the Heavens",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45512",["loot_name"] = "Grips of the Unbroken",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45520",["loot_name"] = "Handwraps of the Vigilant",["loot_value"] = "BIS Support",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45502",["loot_name"] = "Helm of the Faceless",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45509",["loot_name"] = "Idol of the Corruptor",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45145",["loot_name"] = "Libram of the Sacred Shield",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45498",["loot_name"] = "Lotrafen, Spear of the Damned",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45514",["loot_name"] = "Mantle of the Unknowing",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45503",["loot_name"] = "Metallic Loop of the Sufferer",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45517",["loot_name"] = "Pendulum of Infinity",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45515",["loot_name"] = "Ring of the Vacant Eye",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45511",["loot_name"] = "Scepter of Lost Souls",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45507",["loot_name"] = "The General's Heart",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45519",["loot_name"] = "Vestments of the Blind Denizen",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45516",["loot_name"] = "Voldrethar, Dark Blade of Oblivion",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Vezax",},
{["loot_id"]="45522",["loot_name"] = "Blood of the Old God",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45524",["loot_name"] = "Chestguard of Insidious Intent",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45531",["loot_name"] = "Chestguard of the Fallen God",["loot_value"] = "HPal - Bis No HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45532",["loot_name"] = "Cowl of Dark Whispers",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45533",["loot_name"] = "Dark Edge of Depravity",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45521",["loot_name"] = "Earthshaper",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45523",["loot_name"] = "Garona's Guise",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45525",["loot_name"] = "Godbane Signet",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45536",["loot_name"] = "Legguards of Cunning Deception",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45656",["loot_name"] = "Mantle of the Wayward Conqueror",["loot_value"] = "HPal - Bis Phase / BIS NO HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45657",["loot_name"] = "Mantle of the Wayward Protector",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45658",["loot_name"] = "Mantle of the Wayward Vanquisher",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45693",["loot_name"] = "Mimiron's Head",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45897",["loot_name"] = "Reforged Hammer of Ancient Kings",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45530",["loot_name"] = "Sanity's Bond",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45534",["loot_name"] = "Seal of the Betrayed King",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45529",["loot_name"] = "Shawl of Haunted Memories",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45535",["loot_name"] = "Show of Faith",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45527",["loot_name"] = "Soulscribe",["loot_value"] = "",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45537",["loot_name"] = "Treads of the False Oracle",["loot_value"] = "Hpal - Bis HM",["loot_zone"] = "Ulduar N25",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46340",["loot_name"] = "Adamant Handguards",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Trash",},
{["loot_id"]="46351",["loot_name"] = "Bloodcrush Cudgel",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Trash",},
{["loot_id"]="46346",["loot_name"] = "Boots of Unsettled Prey",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Trash",},
{["loot_id"]="46345",["loot_name"] = "Bracers of Righteous Reformation",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Trash",},
{["loot_id"]="46347",["loot_name"] = "Cloak of the Dormant Blaze",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Trash",},
{["loot_id"]="46341",["loot_name"] = "Drape of the Spellweaver",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Trash",},
{["loot_id"]="46343",["loot_name"] = "Fervor of the Protectorate",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Trash",},
{["loot_id"]="46342",["loot_name"] = "Golemheart Longbow",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Trash",},
{["loot_id"]="46344",["loot_name"] = "Iceshear Mantle",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Trash",},
{["loot_id"]="46339",["loot_name"] = "Mimiron's Repeater",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Trash",},
{["loot_id"]="46350",["loot_name"] = "Pillar of Fortitude",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Trash",},
{["loot_id"]="45100",["loot_name"] = "Pattern: Belt of Arctic Life",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45094",["loot_name"] = "Pattern: Belt of Dragons",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45096",["loot_name"] = "Pattern: Blue Belt of Chaos",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45095",["loot_name"] = "Pattern: Boots of Living Scale",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45101",["loot_name"] = "Pattern: Boots of Wintry Endurance",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45104",["loot_name"] = "Pattern: Cord of the White Dawn",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45098",["loot_name"] = "Pattern: Death-warmed Belt",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45099",["loot_name"] = "Pattern: Footpads of Silence",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45097",["loot_name"] = "Pattern: Lightning Grounded Boots",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45102",["loot_name"] = "Pattern: Sash of Ancient Power",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45105",["loot_name"] = "Pattern: Savior's Slippers",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45103",["loot_name"] = "Pattern: Spellslinger's Slippers",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45089",["loot_name"] = "Plans: Battlelord's Plate Boots",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45088",["loot_name"] = "Plans: Belt of the Titans",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45092",["loot_name"] = "Plans: Indestructible Plate Girdle",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45090",["loot_name"] = "Plans: Plate Girdle of Righteousness",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45093",["loot_name"] = "Plans: Spiked Deathdealers",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45091",["loot_name"] = "Plans: Treads of Destiny",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Recipes",},
{["loot_id"]="45087",["loot_name"] = "Runed Orb",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Tokens",},
{["loot_id"]="45291",["loot_name"] = "Combustion Bracers",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45292",["loot_name"] = "Energy Siphon",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45287",["loot_name"] = "Firesoul",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45288",["loot_name"] = "Firestrider Chestguard",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45283",["loot_name"] = "Flamewatch Armguards",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45295",["loot_name"] = "Gilded Steel Legplates",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45293",["loot_name"] = "Handguards of Potent Cures",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45282",["loot_name"] = "Ironsoul",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45284",["loot_name"] = "Kinetic Ripper",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45289",["loot_name"] = "Lifespark Visage",["loot_value"] = "Great",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45300",["loot_name"] = "Mantle of Fiery Vengeance",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45285",["loot_name"] = "Might of the Leviathan",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45286",["loot_name"] = "Pyrite Infuser",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45297",["loot_name"] = "Shimmering Seal",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45296",["loot_name"] = "Twirling Blades",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Leviathan",},
{["loot_id"]="45316",["loot_name"] = "Armbraces of the Vibrant Flame",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Ignis",},
{["loot_id"]="45318",["loot_name"] = "Drape of Fuming Anger",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Ignis",},
{["loot_id"]="45313",["loot_name"] = "Furnace Stone",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Ignis",},
{["loot_id"]="45310",["loot_name"] = "Gauntlets of the Iron Furnace",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Ignis",},
{["loot_id"]="45312",["loot_name"] = "Gloves of Smoldering Touch",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Ignis",},
{["loot_id"]="45314",["loot_name"] = "Igniter Rod",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Ignis",},
{["loot_id"]="45321",["loot_name"] = "Pauldrons of Tempered Will",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Ignis",},
{["loot_id"]="45311",["loot_name"] = "Relentless Edge",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Ignis",},
{["loot_id"]="45309",["loot_name"] = "Rifle of the Platinum Guard",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Ignis",},
{["loot_id"]="45317",["loot_name"] = "Shawl of the Caretaker",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Ignis",},
{["loot_id"]="45303",["loot_name"] = "Band of Draconic Guile",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45306",["loot_name"] = "Binding of the Dragon Matriarch",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45301",["loot_name"] = "Bracers of the Smothering Inferno",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45305",["loot_name"] = "Breastplate of the Afterlife",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45299",["loot_name"] = "Dragonsteel Faceplate",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45308",["loot_name"] = "Eye of the Broodmother",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45307",["loot_name"] = "Ironscale Leggings",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45298",["loot_name"] = "Razorscale Talon",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45304",["loot_name"] = "Stormtempered Girdle",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45302",["loot_name"] = "Treads of the Invader",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Razorscale",},
{["loot_id"]="45868",["loot_name"] = "Aesir's Edge",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45680",["loot_name"] = "Armbands of the Construct",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45867",["loot_name"] = "Breastplate of the Stoneshaper",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45676",["loot_name"] = "Chestplate of Vicious Potency",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45694",["loot_name"] = "Conductive Cord",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45869",["loot_name"] = "Fluxing Energy Coils",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45679",["loot_name"] = "Gloves of Taut Grip",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45687",["loot_name"] = "Helm of Veiled Energies",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45870",["loot_name"] = "Magnetized Projectile Emitter",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45685",["loot_name"] = "Plasma Foil",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45675",["loot_name"] = "Power Enhancing Loop",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45682",["loot_name"] = "Pulsing Spellshield",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45871",["loot_name"] = "Seal of Ulduar",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45677",["loot_name"] = "Treacherous Shoulderpads",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45686",["loot_name"] = "Vest of the Glowing Crescent",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "XT-002",},
{["loot_id"]="45506",["loot_name"] = "Archivum Data Disc",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45455",["loot_name"] = "Belt of the Crystal Tree",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45333",["loot_name"] = "Belt of the Iron Servant",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45378",["loot_name"] = "Boots of the Petrified Forest",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45329",["loot_name"] = "Circlet of True Sight",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45322",["loot_name"] = "Cloak of the Iron Council",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45330",["loot_name"] = "Greaves of Iron Intensity",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45418",["loot_name"] = "Lady Maye's Sapphire Ring",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45324",["loot_name"] = "Leggings of Swift Reflexes",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45456",["loot_name"] = "Loop of the Agile",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45448",["loot_name"] = "Perilous Bite",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45331",["loot_name"] = "Rune-Etched Nightblade",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45423",["loot_name"] = "Runetouch Wristwraps",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45332",["loot_name"] = "Stormtip",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45449",["loot_name"] = "The Masticator",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45447",["loot_name"] = "Watchful Eye of Fate",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Assembly",},
{["loot_id"]="45702",["loot_name"] = "Emerald Signet Ring",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45701",["loot_name"] = "Greaves of the Earthbinder",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45696",["loot_name"] = "Mark of the Unyielding",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45699",["loot_name"] = "Pendant of the Piercing Glare",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45698",["loot_name"] = "Sabatons of the Iron Watcher",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45704",["loot_name"] = "Shawl of the Shattered Giant",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45697",["loot_name"] = "Shoulderguards of the Solemn Watch",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45703",["loot_name"] = "Spark of Hope",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45695",["loot_name"] = "Spire of Withering Dreams",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45700",["loot_name"] = "Stoneguard",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Kologarn",},
{["loot_id"]="45708",["loot_name"] = "Archaedas' Lost Legplates",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45712",["loot_name"] = "Chestplate of Titanic Fury",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45864",["loot_name"] = "Cover of the Keepers",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45866",["loot_name"] = "Elemental Focus Stone",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45711",["loot_name"] = "Ironaya's Discarded Mantle",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45832",["loot_name"] = "Mantle of the Preserver",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45709",["loot_name"] = "Nimble Climber's Belt",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45713",["loot_name"] = "Nurturing Touch",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45865",["loot_name"] = "Raiments of the Corrupted",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Auriaya",},
{["loot_id"]="45707",["loot_name"] = "Shieldwall of the Breaker",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Auriaya",},
{["loot_id"]="46048",["loot_name"] = "Band of Lights",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46039",["loot_name"] = "Breastplate of the Timeless",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46038",["loot_name"] = "Dark Matter",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46042",["loot_name"] = "Drape of the Messenger",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46043",["loot_name"] = "Gloves of the Endless Dark",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46051",["loot_name"] = "Meteorite Crystal",["loot_value"] = "HPal - Bis HM",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46046",["loot_name"] = "Nebula Band",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46044",["loot_name"] = "Observer's Mantle",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46047",["loot_name"] = "Pendant of the Somber Witness",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46045",["loot_name"] = "Pulsar Gloves",["loot_value"] = "BIS NO HM",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46052",["loot_name"] = "Reply-Code Alpha",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46037",["loot_name"] = "Shoulderplates of the Celestial Watch",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46041",["loot_name"] = "Starfall Girdle",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46050",["loot_name"] = "Starlight Treads",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46040",["loot_name"] = "Strength of the Heavens",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="46049",["loot_name"] = "Zodiac Leggings",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Algalon",},
{["loot_id"]="45941",["loot_name"] = "Chestguard of the Lasher",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Freya",},
{["loot_id"]="45946",["loot_name"] = "Fire Orchid Signet",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Freya",},
{["loot_id"]="45644",["loot_name"] = "Gloves of the Wayward Conqueror",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Freya",},
{["loot_id"]="45645",["loot_name"] = "Gloves of the Wayward Protector",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Freya",},
{["loot_id"]="45646",["loot_name"] = "Gloves of the Wayward Vanquisher",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Freya",},
{["loot_id"]="45943",["loot_name"] = "Gloves of Whispering Winds",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Freya",},
{["loot_id"]="45935",["loot_name"] = "Ironbark Faceguard",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Freya",},
{["loot_id"]="45936",["loot_name"] = "Legplates of Flourishing Resolve",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Freya",},
{["loot_id"]="45294",["loot_name"] = "Petrified Ivy Sprig",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Freya",},
{["loot_id"]="45945",["loot_name"] = "Seed of Budding Carnage",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Freya",},
{["loot_id"]="45947",["loot_name"] = "Serilas, Blood Blade of Invar One-Arm",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Freya",},
{["loot_id"]="45940",["loot_name"] = "Tunic of the Limber Stalker",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Freya",},
{["loot_id"]="45934",["loot_name"] = "Unraveling Reach",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Freya",},
{["loot_id"]="45872",["loot_name"] = "Avalanche",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Hodir",},
{["loot_id"]="45888",["loot_name"] = "Bitter Cold Armguards",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Hodir",},
{["loot_id"]="45464",["loot_name"] = "Cowl of Icy Breaths",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Hodir",},
{["loot_id"]="45454",["loot_name"] = "Frost-bound Chain Bracers",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Hodir",},
{["loot_id"]="45887",["loot_name"] = "Ice Layered Barrier",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Hodir",},
{["loot_id"]="45886",["loot_name"] = "Icecore Staff",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Hodir",},
{["loot_id"]="45650",["loot_name"] = "Leggings of the Wayward Conqueror",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Hodir",},
{["loot_id"]="45651",["loot_name"] = "Leggings of the Wayward Protector",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Hodir",},
{["loot_id"]="45652",["loot_name"] = "Leggings of the Wayward Vanquisher",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Hodir",},
{["loot_id"]="45876",["loot_name"] = "Shiver",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Hodir",},
{["loot_id"]="45874",["loot_name"] = "Signet of Winter",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Hodir",},
{["loot_id"]="45458",["loot_name"] = "Stormedge",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Hodir",},
{["loot_id"]="45877",["loot_name"] = "The Boreal Guard",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Hodir",},
{["loot_id"]="45873",["loot_name"] = "Winter's Frigid Embrace",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Hodir",},
{["loot_id"]="34057",["loot_name"] = "Abyss Crystal",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Thorim",},
{["loot_id"]="45895",["loot_name"] = "Belt of the Blood Pit",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Thorim",},
{["loot_id"]="45930",["loot_name"] = "Combatant's Bootblade",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Thorim",},
{["loot_id"]="45928",["loot_name"] = "Gauntlets of the Thunder God",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Thorim",},
{["loot_id"]="45893",["loot_name"] = "Guise of the Midgard Serpent",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Thorim",},
{["loot_id"]="45927",["loot_name"] = "Handwraps of Resonance",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Thorim",},
{["loot_id"]="45892",["loot_name"] = "Legacy of Thunder",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Thorim",},
{["loot_id"]="45894",["loot_name"] = "Leggings of Unstable Discharge",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Thorim",},
{["loot_id"]="45931",["loot_name"] = "Mjolnir Runestone",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Thorim",},
{["loot_id"]="45933",["loot_name"] = "Pendant of the Shallow Grave",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Thorim",},
{["loot_id"]="45929",["loot_name"] = "Sif's Remembrance",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Thorim",},
{["loot_id"]="45659",["loot_name"] = "Spaulders of the Wayward Conqueror",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Thorim",},
{["loot_id"]="45660",["loot_name"] = "Spaulders of the Wayward Protector",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Thorim",},
{["loot_id"]="45661",["loot_name"] = "Spaulders of the Wayward Vanquisher",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Thorim",},
{["loot_id"]="45975",["loot_name"] = "Cable of the Metrognome",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45982",["loot_name"] = "Fused Alloy Legplates",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45990",["loot_name"] = "Fusion Blade",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45988",["loot_name"] = "Greaves of the Iron Army",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45647",["loot_name"] = "Helm of the Wayward Conqueror",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45648",["loot_name"] = "Helm of the Wayward Protector",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45649",["loot_name"] = "Helm of the Wayward Vanquisher",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45993",["loot_name"] = "Mimiron's Flight Goggles",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45972",["loot_name"] = "Pulse Baton",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45974",["loot_name"] = "Shoulderguards of Assimilation",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45976",["loot_name"] = "Static Charge Handwraps",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45973",["loot_name"] = "Stylish Power Cape",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Mimiron",},
{["loot_id"]="45989",["loot_name"] = "Tempered Mercury Greaves",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Mimiron",},
{["loot_id"]="46035",["loot_name"] = "Aesuga, Hand of the Ardent Champion",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="46009",["loot_name"] = "Bindings of the Depths",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="46008",["loot_name"] = "Choker of the Abyss",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="46010",["loot_name"] = "Darkstone Ring",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="46032",["loot_name"] = "Drape of the Faceless General",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="45997",["loot_name"] = "Gauntlets of the Wretched",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="45996",["loot_name"] = "Hoperender",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="46034",["loot_name"] = "Leggings of Profound Darkness",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="46015",["loot_name"] = "Pendant of Endless Despair",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="46014",["loot_name"] = "Saronite Animus Cloak",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="46011",["loot_name"] = "Shadowbite",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="46033",["loot_name"] = "Tortured Earth",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="46013",["loot_name"] = "Underworld Mantle",["loot_value"] = "Good",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="46012",["loot_name"] = "Vestments of the Piercing Light",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="46036",["loot_name"] = "Void Sabre",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Vezax",},
{["loot_id"]="46016",["loot_name"] = "Abaddon",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46068",["loot_name"] = "Amice of Inconceivable Horror",["loot_value"] = "BIS ALL",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46097",["loot_name"] = "Caress of Insanity",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45635",["loot_name"] = "Chestguard of the Wayward Conqueror",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45636",["loot_name"] = "Chestguard of the Wayward Protector",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="45637",["loot_name"] = "Chestguard of the Wayward Vanquisher",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46018",["loot_name"] = "Deliverance",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46025",["loot_name"] = "Devotion",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46028",["loot_name"] = "Faceguard of the Eyeless Horror",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46067",["loot_name"] = "Hammer of Crushing Whispers",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46024",["loot_name"] = "Kingsbane",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46019",["loot_name"] = "Leggings of the Insatiable",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46022",["loot_name"] = "Pendant of a Thousand Maws",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46021",["loot_name"] = "Royal Seal of King Llane",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46096",["loot_name"] = "Signet of Soft Lament",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46095",["loot_name"] = "Soul-Devouring Cinch",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46031",["loot_name"] = "Touch of Madness",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46030",["loot_name"] = "Treads of the Dragon Council",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
{["loot_id"]="46312",["loot_name"] = "Vanquished Clutches of Yogg-Saron",["loot_value"] = "",["loot_zone"] = "Ulduar N10",["loot_bosses"] = "Yogg-Saron",},
}
